# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "recommendation.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14recommendation.proto\x12\x0erecommendation"8\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\x12\r\n\x05scene\x18\x03 \x01(\t"X\n\x16RecommendationResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12-\n\x05items\x18\x02 \x03(\x0b\x32\x1e.recommendation.ItemPrediction"0\n\x0eItemPrediction\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32r\n\x15RecommendationService\x12Y\n\x12GetRecommendations\x12\x1b.recommendation.UserRequest\x1a&.recommendation.RecommendationResponseB1\n\x18\x63om.example.gateway.grpcB\x13RecommendationProtoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "recommendation_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"\n\030com.example.gateway.grpcB\023RecommendationProtoP\001"
    )
    _globals["_USERREQUEST"]._serialized_start = 40
    _globals["_USERREQUEST"]._serialized_end = 96
    _globals["_RECOMMENDATIONRESPONSE"]._serialized_start = 98
    _globals["_RECOMMENDATIONRESPONSE"]._serialized_end = 186
    _globals["_ITEMPREDICTION"]._serialized_start = 188
    _globals["_ITEMPREDICTION"]._serialized_end = 236
    _globals["_RECOMMENDATIONSERVICE"]._serialized_start = 238
    _globals["_RECOMMENDATIONSERVICE"]._serialized_end = 352
# @@protoc_insertion_point(module_scope)
