---
# Gateway Deployment: Spring Boot API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: scalestyle
  labels:
    app: scalestyle
    component: gateway
    version: "1.0"
spec:
  replicas: 2  # Start with 2 for HPA demo
  selector:
    matchLabels:
      app: scalestyle
      component: gateway
  template:
    metadata:
      labels:
        app: scalestyle
        component: gateway
        version: "1.0"
      annotations:
        # Prometheus scraping annotations
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: gateway
        # Update with your Docker Hub image
        image: your-dockerhub-username/scalestyle-gateway:latest
        imagePullPolicy: Always
        
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        
        # Environment variables from ConfigMap
        envFrom:
        - configMapRef:
            name: scalestyle-config
        
        # Additional environment variables specific to gateway
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        
        # Resource requests and limits
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        
        # Health checks - Spring Boot Actuator endpoints
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 15
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5
        
        # Startup probe for slow JVM startup
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 20  # Allow up to 3.3 minutes for startup
        
        # Graceful shutdown
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10

---
# Gateway Service: ClusterIP for internal access (Ingress will route to this)
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: scalestyle
  labels:
    app: scalestyle
    component: gateway
spec:
  type: ClusterIP
  selector:
    app: scalestyle
    component: gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP  # Sticky sessions for better user experience
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
