"""
Canonical degradation reason vocabulary.

Contract: docs/DEGRADATION_REASONS.md.
Use these values for logs, metrics, and API response metadata.
"""
from enum import Enum


class DegradationReason(str, Enum):
    REDIS_TIMEOUT = "REDIS_TIMEOUT"
    REDIS_UNAVAILABLE = "REDIS_UNAVAILABLE"
    PERSONALIZATION_UNAVAILABLE = "PERSONALIZATION_UNAVAILABLE"
    INFERENCE_TIMEOUT = "INFERENCE_TIMEOUT"
    INFERENCE_UNAVAILABLE = "INFERENCE_UNAVAILABLE"
    CACHE_MISS = "CACHE_MISS"
    STALE_DATA_ALLOWED = "STALE_DATA_ALLOWED"
    DOWNSTREAM_CIRCUIT_OPEN = "DOWNSTREAM_CIRCUIT_OPEN"
    DOWNSTREAM_CAPACITY_REJECTED = "DOWNSTREAM_CAPACITY_REJECTED"
    EMPTY_RESULTS_ALLOWED = "EMPTY_RESULTS_ALLOWED"
